name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Setup and compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.1'   # adjust to your version
          otp-version: '28.0'        # adjust to your version

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-2-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-2-

      - name: Install dependencies and compile
        env:
          MIX_ENV: test
        run: |
          mix deps.get
          mix compile

      - name: List
        run: ls -l _build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.1'   # adjust to your version
          otp-version: '28.0'        # adjust to your version

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-2-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-2-

      - name: Install dependencies (from cache)
        env:
          MIX_ENV: test
        run: ls -l _build

      - name: Install dependencies (from cache)
        env:
          MIX_ENV: test
        run: mix deps.get

      - name: Compile
        env:
          MIX_ENV: test
        run: mix compile

      - name: Setup database
        env:
          MIX_ENV: test
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Run tests
        env:
          MIX_ENV: test
        run: mix test
